# Generated by Django 5.2.4 on 2025-07-12 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calorie_tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='carbs',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='meal',
            name='fat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='meal',
            name='protein',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='meal',
            name='serving_qty',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='meal',
            name='serving_unit',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
