# Generated by Django 5.2.4 on 2025-08-10 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calorie_tracker', '0005_userprofile_email_userprofile_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='activity',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='raw_api_data',
        ),
        migrations.AddField(
            model_name='activity',
            name='activity_type',
            field=models.CharField(choices=[('RUN', 'Bieganie'), ('SWIM', 'Pływanie'), ('CYCLE', 'Jazda na rowerze'), ('GYM', 'Siłownia'), ('OTHER', 'Inne')], default='OTHER', max_length=20),
        ),
        migrations.AddField(
            model_name='activity',
            name='duration',
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AddField(
            model_name='activity',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='calories_burned',
            field=models.PositiveIntegerField(),
        ),
    ]
