# Generated by Django 5.2.4 on 2025-08-10 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calorie_tracker', '0007_alter_activity_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Mężczyzna'), ('K', 'Kobieta')], default=None, max_length=1, null=True),
        ),
    ]
