# Generated by Django 5.2.4 on 2025-08-10 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calorie_tracker', '0008_alter_userprofile_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Mężczyzna'), ('K', 'Kobieta')], default='M', max_length=1, null=True),
        ),
    ]
