# Generated by Django 5.2.4 on 2025-08-15 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calorie_tracker', '0009_alter_userprofile_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='activity_type',
            field=models.CharField(choices=[('RUN', 'Bieganie'), ('SWIM', 'Pływanie'), ('CYCLE', 'Jazda na rowerze'), ('GYM', 'Siłownia'), ('WALKING', 'Spacer'), ('Hiking', 'Chodzenie po górach'), ('Climbing', 'Wspinaczka'), ('OTHER', 'Inne')], default='OTHER', max_length=20),
        ),
    ]
