# Generated by Django 5.2.4 on 2025-08-15 13:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calorie_tracker', '0010_alter_activity_activity_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
