# Generated by Django 5.2.4 on 2025-08-15 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calorie_tracker', '0011_alter_meal_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meal',
            options={'ordering': ['-date', '-id']},
        ),
    ]
